name: Daily Drive Upload

on:
  schedule:
    - cron: '0 7 * * *'  # Runs daily at 7:00 AM UTC = 12:30 PM IST
  workflow_dispatch:       # Allows manual trigger

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python current_time_script.py

    - name: Upload token.json (optional backup)
      uses: actions/upload-artifact@v3
      with:
        name: token
        path: token.json
