name: Daily Drive Upload

on:
  schedule:
    - cron: '7 7 * * *'  # 12:37 PM IST (7:07 AM UTC)
  workflow_dispatch:       # Allows manual trigger from GitHub

jobs:
  run_script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script
      run: python current_time_script.py

    - name: Upload token.json (optional backup)
      uses: actions/upload-artifact@v4
      with:
        name: token
        path: token.json
